spring:
  datasource:
    password: yash1234
    url: jdbc:mysql://database-1.cghscqwgostc.us-east-1.rds.amazonaws.com:3306/hr
    username: admins
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
